export const Operators = {
    ROYALPARI: {
        NAME: "ROYAL PARI",
        ORDER_NUMBER: 1,
        OPERATOR_LOGO_ICON_URL: 'https://www.thepunterspage.com/goto/parimatch-sports-grdt/?referrer=https://www.thepunterspage.com/#table',
        OPERATOR_LOGO_TITLE: "Parimatch logo",
        EXPECTED_URL: "https://www.parimatch.co.uk/aff/football-welcome-offer-t-p?",
        REVIEW_NAME: "Read Parimatch Review",
        REVIEW_URL: 'https://www.thepunterspage.com/parimatch-review/',
    },
    BETVICTOR: {
        NAME: "BETVICTOR",
        ORDER_NUMBER: 2,
        OPERATOR_LOGO_ICON_URL: 'https://www.thepunterspage.com/goto/betvictor-sports-grdt/?referrer=https://www.thepunterspage.com/&referrer=https://www.thepunterspage.com/#table',
        EXPECTED_URL: "https://www.betvictor.com/aff/football-welcome-offer-bet-10-get-40-nt48-p?",
        OPERATOR_LOGO_TITLE: "Bet Victor logo",
        REVIEW_NAME: "Read BetVictor Review",
        REVIEW_URL: 'https://www.thepunterspage.com/betvictor-review/',
    },
    THEPOOLS: {
        NAME: "THEPOOLS",
        ORDER_NUMBER: 3,
        OPERATOR_LOGO_ICON_URL: 'https://www.thepunterspage.com/goto/thepools-sports-grtd/?referrer=https://www.thepunterspage.com/&referrer=https://www.thepunterspage.com/#table',
        EXPECTED_URL: "https://www.thepools.com/sports-and-racing-offers?",
        OPERATOR_LOGO_TITLE: "the pools logo",
        REVIEW_NAME: "Read The Pools Review",
        REVIEW_URL: 'https://www.thepunterspage.com/the-pools-review/',
    },
    SPORTINGBET: {
        NAME: "SPORTINGBET",
        ORDER_NUMBER: 4,
        OPERATOR_LOGO_ICON_URL: 'https://www.thepunterspage.com/goto/sportingbet-sports-grdt/?referrer=https://www.thepunterspage.com/#table',
        EXPECTED_URL: "https://promo.sportingbet.com/en/promo/p/sports/uk/welcome-challenge?",
        OPERATOR_LOGO_TITLE: "sportingbet logo",
        REVIEW_NAME: "Read Sportingbet Review",
        REVIEW_URL: 'https://www.thepunterspage.com/sportingbet-review/',
    },
    SPREADEX: {
        NAME: "SPREADEX",
        ORDER_NUMBER: 5,
        OPERATOR_LOGO_ICON_URL: 'https://www.thepunterspage.com/goto/spreadex-sports-grdt/?referrer=https://www.thepunterspage.com/#table',
        EXPECTED_URL: "https://www.spreadex.com/sports/en-GB/spread-betting?",
        OPERATOR_LOGO_TITLE: "Spreadex Logo",
        REVIEW_NAME: "Read Spreadex Review",
        REVIEW_URL: 'https://www.thepunterspage.com/spreadex-review/',
    },
    BETUK: {
        NAME: "BETUK",
        ORDER_NUMBER: 6,
        OPERATOR_LOGO_ICON_URL: 'https://www.thepunterspage.com/goto/betuk-sports-grdt/?referrer=https://www.thepunterspage.com/#table',
        EXPECTED_URL: "https://www.betuk.com/betting?",
        OPERATOR_LOGO_TITLE: "BetUK Logo",
        REVIEW_NAME: "Read Bet UK Review",
        REVIEW_URL: 'https://www.thepunterspage.com/betuk-review/',
    }
}